### ISSUE TITLE
dataProvider error

### ISSUE THREAD

**Issue by antoniusz** [3nids/postgres91plusauditor#10]
hi, i am getting this error on loading the plugin in qgis master and 2.14

AttributeError: 'TileLayer' object has no attribute 'dataProvider' 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 306, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/toni/.qgis2/python/plugins/postgres91plusauditor/**init**.py", line 11, in classFactory
    return Postgres91plusAuditor(iface)
  File "/home/toni/.qgis2/python/plugins/postgres91plusauditor/postgres91plusauditor.py", line 20, in **init**
    self.addLayersActions()
  File "/home/toni/.qgis2/python/plugins/postgres91plusauditor/postgres91plusauditor.py", line 66, in addLayersActions
    if layer.dataProvider().name() == "postgres":
AttributeError: 'TileLayer' object has no attribute 'dataProvider'

**Comment by 3nids** [comment]
The plugin is deprecated and is not maintained anymore.
Sorry for the troubles.
Hopefuly a new solution should arise later this year.
