### ISSUE TITLE
Viewing audit history with "Insert" checked in advanced search causes an error

### ISSUE THREAD

**Issue by archaeogeek** [3nids/postgres91plusauditor#8]
QGIS 2.8 on windows 2008 R2 server. If the advanced search section is NOT expanded, or if the "Insert" check box is selected in the advanced search, then the audit history fails with a python error (see below). If the "Insert" checkbox is unchecked then the audit history is correctly shown (without the insert actions). I wonder if it's because there's nothing stored in the changed_fields column in the logged_actions table for an insert?

An error has occured while executing Python code:

Traceback (most recent call last):
  File "C:/Users/Administrator/.qgis2/python/plugins\postgres91plusauditor\gui\auditdialog.py", line 140, in on_searchButton_clicked
    self.displayLoggedActions()
  File "C:/Users/Administrator/.qgis2/python/plugins\postgres91plusauditor\gui\auditdialog.py", line 150, in displayLoggedActions
    self.loggedActionsTable.displayRows(self.results)
  File "C:/Users/Administrator/.qgis2/python/plugins\postgres91plusauditor\gui\loggedactionstable.py", line 61, in displayRows
    dataStr = eval("row.%s()" % crn)
  File "", line 1, in 
  File "C:/Users/Administrator/.qgis2/python/plugins\postgres91plusauditor\core\logresultrow.py", line 93, in changedGeometryStr
    if self.changedGeometry():
  File "C:/Users/Administrator/.qgis2/python/plugins\postgres91plusauditor\core\logresultrow.py", line 89, in changedGeometry
    geometry = self.getFieldValue(data, self.geomColumn)
  File "C:/Users/Administrator/.qgis2/python/plugins\postgres91plusauditor\core\logresultrow.py", line 33, in getFieldValue
    p = fieldRe(fieldName).search(data)
TypeError: expected string or buffer

Python version:
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]

QGIS version:
2.8.6-Wien Wien, e72e2ab

**Comment by 3nids** [comment]
The plugin is deprecated and is not maintained anymore.
Sorry for the troubles.
Hopefuly a new solution should arise later this year.
